deployment:
  tasks:
    - export DEPLOYPATH=/home/zertno/public_html/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R scripts.js $DEPLOYPATH
    - /bin/cp -R style.css $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH





